#%RAML 1.0 NamedExample

value:
-
  id: 0
  firstName: FirstName 
  lastName: LastName 
  address: 12334 address 
  postal: 45454 
  country: Addis Ababa 
  miles: 23 
  creationDate: 2016-01-04T12:48:19+00:00
  type: Personal
- 
  id: 1
  firstName: FirstName1 
  lastName: LastName1
  address: 12334 address 
  postal: 45454 
  country: Addis Ababa 
  miles: 23 
  creationDate: 2016-01-04T12:48:19+00:00
  type: Personal