#%RAML 1.0 NamedExample

value:
-
  firstName: Robel
  lastName: LastName 
  address: 12334 address 
  postal: 12345
  country: Addis Ababa 
  miles: 23 
  Type: Personal
-
  firstName: SecondRobel
  lastName: LastName 
  address: 12334 address 
  postal: 12345
  country: Addis Ababa 
  miles: 23 
  Type: Bussiness